spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&autoReconnectForPools=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    name: test
    username: test
    # password: -Dspring.datasource.password=XXXX
  logging:
    jdbc:
      sqlonly: on
  jooq:
    sql-dialect: MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    credentials:
      accessKey: xx
      secretKey: xx
    stack:
      auto: false
    region:
      static: eu-west-1
      auto: false