/*
 * This file is generated by jOOQ.
 */
package io.github.yuizho.springsandbox.repositories.jooq.schema;


import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.Division;
import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.Product;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DIVISION_PRIMARY = Indexes0.DIVISION_PRIMARY;
    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCT_UK_PRODUCT = Indexes0.PRODUCT_UK_PRODUCT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DIVISION_PRIMARY = Internal.createIndex("PRIMARY", Division.DIVISION, new OrderField[] { Division.DIVISION.ID }, true);
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT, new OrderField[] { Product.PRODUCT.ID }, true);
        public static Index PRODUCT_UK_PRODUCT = Internal.createIndex("uk_product", Product.PRODUCT, new OrderField[] { Product.PRODUCT.DIVISION, Product.PRODUCT.CREATED }, true);
    }
}
