/*
 * This file is generated by jOOQ.
 */
package io.github.yuizho.springsandbox.repositories.jooq.schema;


import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.Division;
import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.Product;
import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.records.DivisionRecord;
import io.github.yuizho.springsandbox.repositories.jooq.schema.tables.records.ProductRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DivisionRecord, UInteger> IDENTITY_DIVISION = Identities0.IDENTITY_DIVISION;
    public static final Identity<ProductRecord, UInteger> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DivisionRecord> KEY_DIVISION_PRIMARY = UniqueKeys0.KEY_DIVISION_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_UK_PRODUCT = UniqueKeys0.KEY_PRODUCT_UK_PRODUCT;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProductRecord, DivisionRecord> FK_DIVISION = ForeignKeys0.FK_DIVISION;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DivisionRecord, UInteger> IDENTITY_DIVISION = Internal.createIdentity(Division.DIVISION, Division.DIVISION.ID);
        public static Identity<ProductRecord, UInteger> IDENTITY_PRODUCT = Internal.createIdentity(Product.PRODUCT, Product.PRODUCT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DivisionRecord> KEY_DIVISION_PRIMARY = Internal.createUniqueKey(Division.DIVISION, "KEY_division_PRIMARY", Division.DIVISION.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, "KEY_product_PRIMARY", Product.PRODUCT.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_UK_PRODUCT = Internal.createUniqueKey(Product.PRODUCT, "KEY_product_uk_product", Product.PRODUCT.DIVISION, Product.PRODUCT.CREATED);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ProductRecord, DivisionRecord> FK_DIVISION = Internal.createForeignKey(io.github.yuizho.springsandbox.repositories.jooq.schema.Keys.KEY_DIVISION_PRIMARY, Product.PRODUCT, "fk_division", Product.PRODUCT.DIVISION);
    }
}
